trigger:
  branches:
    include:
    - main

variables:
- group: shared

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy
  displayName: Deploy with Terraform
  jobs:
    - job: apply
      displayName: Terraform Apply
      pool:
        vmImage: ubuntu-latest
      steps:
      # Terraform init with backend set to to use Azure Blob storage
      - checkout: self
        displayName: Checkout Terraform Module
      - task: TerraformTaskV4@4
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: '$(SERVICE_CONNECTION)'
          backendAzureRmResourceGroupName: '$(BACKEND_RESOURCE_GROUP)'
          backendAzureRmStorageAccountName: '$(BACKEND_STORAGE_ACCOUNT)'
          backendAzureRmContainerName: '$(BACKEND_STORAGE_CONTAINER)'
          backendAzureRmKey: '$(BACKEND_KEY)'

      # Apply Terraform changes only on the main branch
      - task: TerraformTaskV4@4
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '-auto-approve'
          environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'